image: python:3.11-slim-bookworm

pipelines:
  branches:
    main:
      - step:
          name: Security Scan
          script:
            # Run a security scan for sensitive data.
            # See more security tools at https://bitbucket.org/product/features/pipelines/integrations?&category=security
            - pipe: atlassian/git-secrets-scan:0.4.3
      - step:
          name: Run pytest
          script:
            - pip install -r tests/requirements.txt
            - pytest tests
      - step:
          name: Build Documentation
          script:
            - pip install -r docs/requirements.txt
            - cd docs
            - sphinx-build -b html . _build
          artifacts:
            - docs/_build/**
      - step:
          name: Deploy Documentation to S3
          deployment: production
          script:
            - pipe: atlassian/aws-s3-deploy:0.3.8
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: 'us-east-1'
                S3_BUCKET: 'boomi-cicd-cli-py'
                LOCAL_PATH: 'docs/_build'
  default:
    - step:
        name: Security Scan
        script:
          # Run a security scan for sensitive data.
          # See more security tools at https://bitbucket.org/product/features/pipelines/integrations?&category=security
          - pipe: atlassian/git-secrets-scan:0.4.3
    - step:
        name: Run pytest
        script:
          - pip install -r tests/requirements.txt
          - pytest tests
    - step:
        name: Build Documentation
        script:
          - pip install -r docs/requirements.txt
          - cd docs
          - sphinx-build -b html . _build
        artifacts:
          - docs/_build/**
    - step:
        name: Deploy Documentation to S3
        deployment: staging
        script:
          - pipe: atlassian/aws-s3-deploy:0.3.8
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: 'us-east-1'
              S3_BUCKET: 'boomi-cicd-cli-py-dev'
              LOCAL_PATH: 'docs/_build'